#!/usr/bin/env python3

import sys, os

# Make sure we are in same directory as this file
# Note realpath is needed to resolve symbolic links
os.chdir(os.path.dirname(os.path.realpath(__file__)))

# Read test result from file
with open('test_result.txt', 'r') as f:
    fail = int(f.read())

# let's fake failing test for now 
print("Running tests (python)")
print("............................")
print("Failed!" if fail else "Passed!")
sys.exit(fail)
