#!/usr/bin/env python3

import sys, os

# magic line to ensure that we're always inside the root of our application,
# no matter from which directory we'll run script
# thanks to it we can just enter `./scripts/run-tests.sh`
os.chdir(os.path.dirname(os.path.realpath(__file__)))

# let's fake failing test for now 
print("Running tests")
print("............................")
print("Failed!")
sys.exit(1)
